name: CelestialWhitelister
version: '${version}'
main: dev.celestelove.whitelister.CelestialWhitelister
api-version: '1.21'
authors: [ CelesteLove ]
loader: dev.celestelove.whitelister.CelestialWhitelisterClassLoader

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
